# BLOQUE 02 – Análisis de movilidad
## Objetivo
Integrar las capas de la previa etapa en un solo geopackage, y realizar el filtrado de lo que se necesitará en la etapa 3.
## Inputs
- 1_D2C1_Poblacion.gpkg
- 1_D2C2_Económico.gpkg
## Procesos
- Integración
- Filtrado
## Output
- 2_Dimensiones.gpkg
    - 2_D4_Movilidad.shp

In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np

In [2]:
ruta_movilidad = r"C:\Users\alflo\Desktop\DAL_LAB\outputs\etapa_1\1_D4C1_Movilidad.gpkg"

ruta_salida = r"C:\Users\alflo\Desktop\DAL_LAB\outputs\etapa_2\2_Dimensiones.gpkg"

# Carga de datos

In [3]:
gpd.list_layers(ruta_movilidad)

                          name    geometry_type
0           1_D4C1V1_ciclovias  MultiLineString
1   1_D4C1V1_estaciones_mibici            Point
2  1_D4C1V2_transporte_público  MultiLineString
3     1_D4C1V3_estructura_vial  MultiLineString

In [4]:
cv = gpd.read_file(ruta_movilidad, layer = "1_D4C1V1_ciclovias")
mibici = gpd.read_file(ruta_movilidad, layer = "1_D4C1V1_estaciones_mibici")
tp = gpd.read_file(ruta_movilidad, layer = "1_D4C1V2_transporte_público")
vial = gpd.read_file(ruta_movilidad, layer = "1_D4C1V3_estructura_vial")

In [5]:
cv.columns

Index(['nombre_de_', 'municipio', 'Categoría', 'geometry'], dtype='object')

In [6]:
mibici.columns

Index(['clave_de_i', 'Categoría', 'geometry'], dtype='object')

In [8]:
tp.columns

Index(['Tipo', 'Categoría', 'geometry'], dtype='object')

In [9]:
vial.columns

Index(['Categoría', 'geometry'], dtype='object')

In [23]:
mibici

    clave_de_i         Categoría                        geometry
0      GDL-001  estación_mi_bici  POINT (672001.602 2286100.363)
1      GDL-002  estación_mi_bici  POINT (670210.664 2286176.344)
2      GDL-003  estación_mi_bici  POINT (669975.515 2286225.128)
3      GDL-004  estación_mi_bici  POINT (670542.741 2288905.316)
4      GDL-005  estación_mi_bici  POINT (672970.189 2287746.561)
..         ...               ...                             ...
363    ZPN-077  estación_mi_bici  POINT (664401.277 2284850.882)
364    GDL-276  estación_mi_bici  POINT (668603.483 2286609.597)
365    GDL-280  estación_mi_bici  POINT (667880.422 2287071.264)
366    GDL-279  estación_mi_bici  POINT (672275.714 2289056.494)
367    GDL-281  estación_mi_bici   POINT (673569.74 2289293.547)

[368 rows x 3 columns]

In [24]:
cv['Tipo'] = 'Ciclovía'
tp['Tipo'] = 'Trans_Publico'
vial['Tipo'] = 'Vialidad'

mibici['Tipo'] = 'Estación Bici'
mibici = mibici[['Tipo','Categoría', 'geometry']]

# Unión a un solo df, extracción de columnas de interés

In [21]:
df = pd.concat([cv[['Tipo','Categoría', 'geometry']], tp[['Tipo','Categoría', 'geometry']], vial[['Tipo','Categoría', 'geometry']]])

# filtrado estado y municipios

In [76]:
# # EXTRAER JALISCO
# ue_ent = ue[ue['cve_ent'] == '14'].copy()
# eq_ent = eq[eq['CVE_ENT'] == '14'].copy()

# # Lista de municipios AMG
# municipios = ['002','039', '044', '051','070','097', '098', '101', '120', '124']

# # Filtrar el DataFrame solo con los municipios de interés
# ue_mun = ue_ent[
#     (ue_ent['cve_mun'].isin(municipios)) & 
#     (ue_ent['cve_ent'] == '14')
# ]

# eq_mun = eq_ent[
#     (eq_ent['CVE_MUN'].isin(municipios)) & 
#     (eq_ent['CVE_ENT'] == '14')
# ]

In [82]:
# Reemplazar * con 1
def replace(dataframe):
    return dataframe.replace('*', '1')

# Limpiar *
ue_mun = replace(ue_mun)
eq_mun = replace(eq_mun)

# Reemplazar N/D
ue_mun = ue_mun.replace('N/D', np.nan)
eq_mun = eq_mun.replace('N/D', np.nan)

# Actualizar valores sin información de "null" a 0
ue_mun = ue_mun.fillna(0)
eq_mun = eq_mun.fillna(0)

# Guardado

In [26]:
df.to_file(ruta_salida, layer='2_D4_movilidad_lineas', driver='GPKG')
mibici.to_file(ruta_salida, layer='2_D4_movilidad_puntos', driver='GPKG')